# Generated by Django 3.2 on 2022-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
