# Generated by Django 3.2 on 2022-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
