# Generated by Django 3.2 on 2022-07-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=75, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=2000, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='django_basics.topic')),
            ],
        ),
    ]
