# Generated by Django 3.2 on 2022-07-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0002_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
    ]
