# Generated by Django 3.2 on 2022-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0003_subtopic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='paragraph',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
