# Generated by Django 3.2 on 2022-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0004_alter_subtopic_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
