# Generated by Django 3.2 on 2022-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0005_subtopic_order_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['order_no']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
